# Assignment 2
For this assignment you'll be looking at 2017 data on immunizations from the CDC. Your datafile for this assignment is in [assets/NISPUF17.csv](assets/NISPUF17.csv). A data users guide for this, which you'll need to map the variables in the data to the questions being asked, is available at [assets/NIS-PUF17-DUG.pdf](assets/NIS-PUF17-DUG.pdf). **Note: you may have to go to your Jupyter tree (click on the Coursera image) and navigate to the assignment 2 assets folder to see this PDF file).**

## Question 1
Write a function called `proportion_of_education` which returns the proportion of children in the dataset who had a mother with the education levels equal to less than high school (<12), high school (12), more than high school but not a college graduate (>12) and college degree.

*This function should return a dictionary in the form of (use the correct numbers, do not round numbers):* 
```
    {"less than high school":0.2,
    "high school":0.4,
    "more than high school but not college":0.2,
    "college":0.2}
```


In [1]:
import pandas as pd

df=pd.read_csv('assets/NISPUF17.csv')
df.head()

Unnamed: 0  SEQNUMC  SEQNUMHH  PDAT    PROVWT_D     RDDWT_D  STRATUM  YEAR  \
0           1   128521     12852     2         NaN  235.916956     1031  2017   
1           2    10741      1074     2         NaN  957.353840     1068  2017   
2           3   220011     22001     2         NaN  189.611299     1050  2017   
3           4    86131      8613     1  675.430817  333.447418     1040  2017   
4           5   227141     22714     1  482.617748  278.768063     1008  2017   

   AGECPOXR  HAD_CPOX  ...  XVRCTY2  XVRCTY3  XVRCTY4  XVRCTY5  XVRCTY6  \
0       NaN         2  ...                        NaN      NaN      NaN   
1       NaN         2  ...                        NaN      NaN      NaN   
2       NaN         2  ...                        NaN      NaN      NaN   
3       NaN         2  ...                        NaN      NaN      NaN   
4       NaN         2  ...                        NaN      NaN      NaN   

   XVRCTY7  XVRCTY8  XVRCTY9  INS_STAT2_I  INS_BREAK_I  
0      NaN      NaN      NaN          NaN          NaN  
1      NaN      NaN      NaN          NaN          NaN  
2      NaN      NaN      NaN          NaN          NaN  
3      NaN      NaN      NaN          1.0          2.0  
4      NaN      NaN      NaN          2.0          1.0  

[5 rows x 454 columns]

In [2]:
df['EDUC1'].unique()

array([4, 3, 1, 2])

In [3]:
import seaborn as sns

sns.countplot(df['EDUC1'].unique())

import matplotlib.pyplot as plt
plt.show()

<Figure size 640x480 with 1 Axes>

In [4]:
len(df.where(cond=df['EDUC1']==2,axis=1))

28465

In [5]:
len(df.loc[df['EDUC1']==2])

4906

In [6]:
len(df)

28465

In [8]:
import numpy as np

def proportion_of_education():
    # your code goes here
    # YOUR CODE HERE
    EDUS=df['EDUC1']
    edus=np.sort(EDUS.values)
    poe={"less than high school":0,
        "high school":0,
        "more than high school but not college":0,
        "college":0}
    n=len(edus)
    poe["less than high school"]=np.sum(edus==1)/n
    poe["high school"]=np.sum(edus==2)/n
    poe["more than high school but not college"]=np.sum(edus==3)/n
    poe["college"]=np.sum(edus==4)/n
    return poe
    
    
    raise NotImplementedError()

In [9]:
assert type(proportion_of_education())==type({}), "You must return a dictionary."
assert len(proportion_of_education()) == 4, "You have not returned a dictionary with four items in it."
assert "less than high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "more than high school but not college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."


## Question 2

Let's explore the relationship between being fed breastmilk as a child and getting a seasonal influenza vaccine from a healthcare provider. Return a tuple of the average number of influenza vaccines for those children we know received breastmilk as a child and those who know did not.

*This function should return a tuple in the form (use the correct numbers:*
```
(2.5, 0.1)
```

In [10]:
df['CBF_01'].unique()

array([ 1,  2, 99, 77])

In [12]:
df['P_NUMFLU'].unique()

array([nan,  3.,  0.,  2.,  1.,  4.,  5.,  6.])

In [118]:
def average_influenza_doses():
    # YOUR CODE HERE
    vac=df.loc[df['CBF_01']==1,'P_NUMFLU'].mean(axis=0)
    non=df.loc[df['CBF_01']==2,'P_NUMFLU'].mean(axis=0)
    #print(vac.mean())
    #print(vac.unique())
    res=(vac,non)
    print(res)
    return res
    raise NotImplementedError()

In [116]:
def average_influenza_doses():
    # YOUR CODE HERE
    df_vac=df[(df['CBF_01']==1) | (df['CBF_01']==2) | (df['CBF_01']==77)]
    vac=df_vac['P_NUMFLU'].mean()
    df_not=df[(df['CBF_01']==99)]
    non=df_not['P_NUMFLU'].mean()
    res=(vac,non)
    print((res))
    return res
    raise NotImplementedError()

In [10]:
def average_influenza_doses():
    cbf_flu=df.loc[:,['CBF_01','P_NUMFLU']]
    
    
    cbf_flu1=cbf_flu[cbf_flu['CBF_01'] ==1].dropna()
    cbf_flu2=cbf_flu[cbf_flu['CBF_01'] ==2].dropna()
    
    flu1=cbf_flu1['P_NUMFLU'].values.copy()
    flu1[np.isnan(flu1)] = 0
    f1=np.sum(flu1)/len(flu1)
    
    flu2=cbf_flu2['P_NUMFLU'].values.copy()
    flu2[np.isnan(flu2)] = 0
    f2=np.sum(flu2)/len(flu2)
    
    aid =(f1,f2)
    return aid
#(0.8523098542069207, 0.14350957316002108)

In [11]:
assert len(average_influenza_doses())==2, "Return two values in a tuple, the first for yes and the second for no."


## Question 3
It would be interesting to see if there is any evidence of a link between vaccine effectiveness and sex of the child. Calculate the ratio of the number of children who contracted chickenpox but were vaccinated against it (at least one varicella dose) versus those who were vaccinated but did not contract chicken pox. Return results by sex. 

*This function should return a dictionary in the form of (use the correct numbers):* 
```
    {"male":0.2,
    "female":0.4}
```

Note: To aid in verification, the `chickenpox_by_sex()['female']` value the autograder is looking for starts with the digits `0.0077`.

In [19]:
df['HAD_CPOX'].unique()

array([ 2,  1, 77, 99])

In [21]:
df['P_NUMVRC'].unique()

array([nan,  1.,  0.,  2.,  3.])

In [22]:
df['SEX'].unique()

array([1, 2])

In [55]:
def chickenpox_by_sex():
    # YOUR CODE HERE
    res={}
    res['male']=(df.loc[(df['SEX']==1) & (df['HAD_CPOX']==2) & (df['P_NUMVRC']>=1)]).count(axis=0)/(df.loc[(df['SEX']==1) & (df['HAD_CPOX']==1) & (df['P_NUMVRC']>=1)]).count(axis=0)
    res['female']=(df.loc[(df['SEX']==2) & (df['HAD_CPOX']==2) & (df['P_NUMVRC']>=1)]).count(axis=0)/(df.loc[(df['SEX']==2) & (df['HAD_CPOX']==1) & (df['P_NUMVRC']>=1)]).count(axis=0)
    #print(res['male'])
    return res
    raise NotImplementedError()

In [12]:
def chickenpox_by_sex():
    # YOUR CODE HERE
    cpo_sex=df[df['P_NUMVRC'].gt(0) & df['HAD_CPOX'].lt(3)].loc[:,['HAD_CPOX','SEX']]
    #Male 1 Female 2
    cpo1_sex1=len(cpo_sex[(cpo_sex['HAD_CPOX']==1) & (cpo_sex['SEX']==1)])
    cpo1_sex2=len(cpo_sex[(cpo_sex['HAD_CPOX']==1) & (cpo_sex['SEX']==2)])
    cpo2_sex1=len(cpo_sex[(cpo_sex['HAD_CPOX']==2) & (cpo_sex['SEX']==1)])
    cpo2_sex2=len(cpo_sex[(cpo_sex['HAD_CPOX']==2) & (cpo_sex['SEX']==2)])
    
    cbs={"male":0,
        "female":0}
    cbs['male']=cpo1_sex1/cpo2_sex1
    cbs['female']=cpo1_sex2/cpo2_sex2
    return cbs
    raise NotImplementedError()

In [13]:
assert len(chickenpox_by_sex())==2, "Return a dictionary with two items, the first for males and the second for females."


## Question 4
A correlation is a statistical relationship between two variables. If we wanted to know if vaccines work, we might look at the correlation between the use of the vaccine and whether it results in prevention of the infection or disease [1]. In this question, you are to see if there is a correlation between having had the chicken pox and the number of chickenpox vaccine doses given (varicella).

Some notes on interpreting the answer. The `had_chickenpox_column` is either `1` (for yes) or `2` (for no), and the `num_chickenpox_vaccine_column` is the number of doses a child has been given of the varicella vaccine. A positive correlation (e.g., `corr > 0`) means that an increase in `had_chickenpox_column` (which means more no’s) would also increase the values of `num_chickenpox_vaccine_column` (which means more doses of vaccine). If there is a negative correlation (e.g., `corr < 0`), it indicates that having had chickenpox is related to an increase in the number of vaccine doses.

Also, `pval` is the probability that we observe a correlation between `had_chickenpox_column` and `num_chickenpox_vaccine_column` which is greater than or equal to a particular value occurred by chance. A small `pval` means that the observed correlation is highly unlikely to occur by chance. In this case, `pval` should be very small (will end in `e-18` indicating a very small number).

[1] This isn’t really the full picture, since we are not looking at when the dose was given. It’s possible that children had chickenpox and then their parents went to get them the vaccine. Does this dataset have the data we would need to investigate the timing of the dose?

In [18]:
def corr_chickenpox():
    import scipy.stats as stats
    import numpy as np
    import pandas as pd
    
    df = pd.read_csv("assets/NISPUF17.csv", index_col=0)
    df=df[df['HAD_CPOX'].lt(3)].loc[:,['HAD_CPOX','P_NUMVRC']].dropna()
    df.columns=['had_chickenpox_column','num_chickenpox_vaccine_column']
    # here is some stub code to actually run the correlation
    corr, pval=stats.pearsonr(df["had_chickenpox_column"],df["num_chickenpox_vaccine_column"])
    
    # just return the correlation
    return corr
    raise NotImplementedError()

In [19]:
assert -1<=corr_chickenpox()<=1, "You must return a float number between -1.0 and 1.0."
